version: '3.2'

networks:
  database-network:
    external: true

services:
  db:
    image: mysql:8
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    env_file:
      - .env.db
    volumes:
      - ./backups:/backups:rw
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - database-network
