version: '3.2'

networks:
  database-network:
    external: true

services:
  db:
    image: postgres:12-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env.db
    volumes:
      - ./backups:/backups:rw
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - database-network
